function [E,M1,M2,M3,r]=efficientTOMP(A,B,C,Y,tmax,eps,itermax)
    M1=[];
    M2=[];
    M3=[];
    [I1,J1]=size(A);
    [I2,J2]=size(B);
    [I3,J3]=size(C);
    R=tensor(Y);
    y=unfold(tensor(Y),3);
    t=1;
    r(1)=1;
    while length(M1)*length(M2)*length(M3)<tmax && r(t)>eps && t<itermax
        S=ttm(R,{A',B',C'});
        S(M1,M2,M3)=0;
        [M,ii1]=max(abs(double(S)));
        [M,ii2]=max(M);
        [M,ii3]=max(M);
        m3=ii3;
        m2=ii2(m3);
        m1=ii1(m2);
        M1=[M1,m1];
        M2=[M2,m2];
        M3=[M3,m3];
        D1=A(:,M1);
        D2=B(:,M2);
        D3=C(:,M3);
        % res=kron(D2,D1)\y;
        % e=res/D3';
        % E=reshape(e,length(M1),length(M2),length(M3));
        % E=tensor(E,[length(M1),length(M2),length(M3)]);
        res=D3\y;
        e=res/kron(D2,D1)';
        E=reshape(e',length(M1),length(M2),length(M3));     %CORRETTO!!!
        E=tensor(E,[length(M1),length(M2),length(M3)]);
        R=Y-ttm(E,{D1,D2,D3});
        t=t+1;
        r(t)=norm(R);
    end
end